monitor.alsa.rules = [
  {
    matches = [
      {
        device.name = "alsa_card.usb-Generic_USB_Audio-00"
      },
      {
        device.name = "alsa_card.usb-SteelSeries_Arctis_Nova_Pro_Wireless-00"
      }
    ]
    actions = {
      update-props = {
        device.disabled = true
      }
    }
  }
]
