monitor.libpipewire.rules = [
  {
    matches = [
      {
        node.name = "~rcp_.*_in"
      }
    ]
    actions = {
      update-props = {
        # This makes the sink look like 'Hardware' to the session manager
        node.passive = false,
        # This forces WirePlumber to treat moves here as permanent
        node.want-driver = true
      }
    }
  }
]

