monitor.libpipewire.rules = [
  {
    matches = [
      {
        node.name = "~rcp_.*_in"
      }
    ]
    actions = {
      update-props = {
        # Forces WirePlumber to treat these as permanent hardware endpoints
        "priority.session": 3000,
        "priority.driver": 3000,
        "node.passive": false,
        "node.want-driver": true
      }
    }
  }
]

