wireplumber.settings = {
    # Stop remembering and forcing apps to old targets
    "node.stream.restore-target": false,
    # Stop following the 'system' default if an app has been moved
    "linking.follow-default-target": false
}

