wireplumber.settings = {
    # MASTER SWITCH: Treat UI moves as permanent overrides
    "node.restore-default-targets": true,
    "node.stream.restore-target": true,
    # STOP pulling apps back to the system default
    "linking.follow-default-target": false,
    "linking.role-based.allow-moving-streams": true,
    "linking.role-based.default-policy": "none"
}

monitor.libpipewire.rules = [
  {
    matches = [ { media.class = "Stream/Audio/Out" } ]
    actions = {
      update-props = {
        "metadata.proxy": "disabled",
        # FORBID the node from jumping back to System in Pro Audio mode
        "node.dont-fallback": true,
        # Standard anchor properties
        "node.restore-target": true,
        "node.dont-reconnect": false,
        "media.role": ""
      }
    }
  }
]

