wireplumber.profiles = {
  main = {
    # Disable the module that forces 'Music' apps to hardware/system defaults
    "policy.media-role": "disabled"
  }
}

wireplumber.settings = {
    "linking.follow-default-target": false,
    "node.stream.restore-target": true,
    "linking.role-based.allow-moving-streams": true,
    "node.stream.restore-props": true,
    "linking.role-based.default-policy": "none"
}

monitor.libpipewire.rules = [
  {
    matches = [
      { node.name = "~rcp_.*_in" }
    ]
    actions = {
      update-props = {
        # This makes the sink look like 'Hardware' to the session manager
        "node.passive": false,
        # This forces the sink to always process audio (prevents idling)
        "node.always-process": true,
        # This forces WirePlumber to treat moves here as permanent
        "node.want-driver": true
      }
    }
  },
  {
    matches = [ { node.name = "~.*" } ]
    actions = {
      update-props = {
        "node.dont-fallback": true,
        "media.role": "",
        "node.dont-reconnect": false
      }
    }
  }
]
