context.modules = [
  { name = libpipewire-module-loopback
    args = {
      node.description = "RCP Duo System"
      capture.props = { node.name = "rcp_system_in" media.class = "Audio/Sink" audio.position = [ FL FR ] }
      playback.props = {
        node.name = "rcp_system_out"
        target.object = "alsa_output.usb-R__DE_RODECaster_Duo_IT0005785-00.pro-output-1"
        audio.position = [ AUX0 AUX1 ]
        node.dont-reconnect = true
      }
    }
  },
  { name = libpipewire-module-loopback
    args = {
      node.description = "RCP Duo Game"
      capture.props = { node.name = "rcp_game_in" media.class = "Audio/Sink" audio.position = [ FL FR ] }
      playback.props = {
        node.name = "rcp_game_out"
        target.object = "alsa_output.usb-R__DE_RODECaster_Duo_IT0005785-00.pro-output-1"
        audio.position = [ AUX2 AUX3 ]
        node.dont-reconnect = true
      }
    }
  },
  { name = libpipewire-module-loopback
    args = {
      node.description = "RCP Duo Music"
      capture.props = { node.name = "rcp_music_in" media.class = "Audio/Sink" audio.position = [ FL FR ] }
      playback.props = {
        node.name = "rcp_music_out"
        target.object = "alsa_output.usb-R__DE_RODECaster_Duo_IT0005785-00.pro-output-1"
        audio.position = [ AUX4 AUX5 ]
        node.dont-reconnect = true
      }
    }
  },
  { name = libpipewire-module-loopback
    args = {
      node.description = "RCP Duo Chat"
      capture.props = { node.name = "rcp_chat_in" media.class = "Audio/Sink" audio.position = [ FL FR ] }
      playback.props = {
        node.name = "rcp_chat_out"
        target.object = "alsa_output.usb-R__DE_RODECaster_Duo_IT0005785-00.pro-output-0"
        audio.position = [ AUX0 AUX1 ]
        node.dont-reconnect = true
      }
    }
  }
]

