stream.rules = [
  {
    matches = [ { node.name = "~.*" } ]
    actions = {
      update-props = {
        # This is the "Master Key" to make UI choices stick
        node.restore-default-targets = true
        node.dont-reconnect = false
        node.passive = false
      }
    }
  }
]

