node.rules = [
    {
        matches = [
            {
                node.name = "~.*"
            }
        ]
        actions = {
            update-props = {
                node.dont-reconnect = false
            }
        }
    }
]
